project:
  type: book

book:
  title: "TidyCampaigns"
  author: "Adrienne Michelson"
  date: "2/17/2023"
  chapters:
    - index.qmd
    - intro.qmd
    - requirements.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



