# Preface {.unnumbered}

In the last 20 years, the technology surrounding the Democratic ecosystem in America has dramatically changed how political parties and advocacy groups elect leaders at all levels of government. Every four-year Presidential cycle elevates new talent across government, campaigns, and technology. 

Democratic politics does not have an open resource to encourage people in politics to join democratic tech or tech to join democratic tech. Only in recently we are seeing open-sourcing like the python package, Parsons, developed in 2018(?) by those at [The Movement Cooperative, spurred to build open source tech to reduce duplicative efforts](https://move-coop.github.io/parsons/html/stable/index.html). Also by candidate campaigns, [like the Warren tech team's caucus calculator and additions to a texting tool.](https://github.com/Elizabeth-Warren) 

Most intelligence sharing is usually membership-based information, or a nonprofit charges an engineer to attempt to teach others, or a campaign hires a consultant shop at a price. None of these things are bad but can come at an economic or time cost not available to many. One underutilized learning method comes from reading books and working through problems like R for Data Science or Advance R, where the readers learn about how things work and test with a sample data set as they read on. 

With growing opportunities to democratize campaigning; this book is to openly share personal experiences of gaining general interdisciplinary knowledge, technical skills, and tools that have been helpful.

This site will compile an opinionated framework for analysis, data science, data direction, and organizing for people to utilize to further democratic wins up and down the ticket.

Compiling this resource as a Quarto Book with chapters should encourage others who want to contribute directly to it to open source their thoughts to the community as a whole or inspire them to create books of their own. Therefore we can have binders filled with more pathways to success for future generations of compassionate, democratic data leaders across the world.

With the R open-source community and the tidyverse as inspiration, the approach will be to simulate three campaigns style—one local campaign within a county, one at the state level, another at a presidential level. The local campaign chapters include beginner-level data and analysis skills, techniques, and workflows for a Data Director suited for a local or state legislative race. The state level will explore techniques suited for Governor, Senate, Statewide Ballots, and Congressional races where there is incresing technicality. The Presidential campaign chapters include sophisticated road mapping, team management, and skills required to handle data flows in and out of multiple states.

This book will release in chapters and you can follow [the development on the repository branches here.](https://github.com/AdriMichelson/TidyCampaigns/pulls)


To learn more about Quarto books visit <https://quarto.org/docs/books>.
